version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: bank-management-postgres
    environment:
      POSTGRES_DB: bankmanagement
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
